apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:
      
      
jobs:

  job-that-uses-testaction:
    steps:
      - name: step that uses testaction (job step name)
        uses: mluzcabrera/testaction@main
        with:
          string-val: 'test string'
      - name: step that uses testaction 2 (job step name)
        uses: mluzcabrera/testaction@main
        with:
          string-val: 'test string'